#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

GENTOOVER=$(sed 's|/[^/]*$||' <<< $(head -3 <<< $(curl --silent http://www.gtlib.gatech.edu/pub/gentoo/releases/$ARCH/autobuilds/latest-stage3-$ARCH_DEB-openrc.txt) | tail -1))

mkdir -p "$CADMIUMROOT/tmp"
ROOTFS_TAR="http://www.gtlib.gatech.edu/pub/gentoo/releases/$ARCH/autobuilds/$GENTOOVER/stage3-$ARCH_DEB-openrc-$GENTOOVER.tar.xz"
if [ ! -f "$CADMIUMROOT/tmp/stage3-$ARCH_GENTOO-openrc-$GENTOOVER.tar.xz" ]; then
	rm $CADMIUMROOT/tmp/stage3-$ARCH_GENTOO-openrc-$GENTOOVER.tar.xz || true
	wget "$ROOTFS_TAR" -O $CADMIUMROOT/tmp/stage3-$ARCH_GENTOO-openrc-$GENTOOVER.tar.xz
fi

tar xpvf $CADMIUMROOT/tmp/stage3*.tar.xz --xattrs-include='*.*' --numeric-owner -C $DESTDIR

cp --dereference /etc/resolv.conf $DESTDIR/etc/resolv.conf

mount --bind /proc $DESTDIR/proc
mount --rbind /sys $DESTDIR/sys
mount --make-rslave $DESTDIR/sys
mount --rbind /dev $DESTDIR/dev
mount --make-rslave $DESTDIR/dev
mount --bind /run $DESTDIR/run
mount --make-slave $DESTDIR/run

$chroot $DESTDIR $qemu /usr/bin/emerge-webrsync
$chroot $DESTDIR $qemu /usr/bin/emerge --sync

echo '# Added by cadmium due how we build the image and also for convience' >> $DESTDIR/etc/portage/make.conf
echo 'FEATURES="-pid-sandbox candy parallel-fetch"' >> $DESTDIR/etc/portage/make.conf

$chroot $DESTDIR $qemu /usr/bin/emerge -uvDN @world

$chroot $DESTDIR $qemu /usr/bin/emerge -v net-misc/networkmanager sys-kernel/linux-firmware
$chroot $DESTDIR $qemu /sbin/rc-update add NetworkManager default