#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

MIRROR="http://dl-cdn.alpinelinux.org/alpine"
ALPINEAPKVER=$(curl -s $MIRROR/latest-stable/main/$ARCH_ALPINE/ | grep "apk-tools-static" | grep -oP '<a href="[^"]+">([^<]+)' | sed 's/<a href="[^"]\+">//' | sed 's/apk-tools-static-//' | sed 's/.apk//')

mkdir -p "$CADMIUMROOT/tmp"
if [ ! -f apk-tools-static-${ALPINEAPKVER}.apk ]; then
    rm apk-tools-static-${ALPINEAPKVER}.apk
    curl -LO $MIRROR/latest-stable/main/${ARCH_ALPINE}/apk-tools-static-${ALPINEAPKVER}.apk
fi
tar -xvzf apk-tools-static-*.apk -C $CADMIUMROOT/tmp

$qemu $CADMIUMROOT/tmp/sbin/apk.static -X $MIRROR/latest-stable/main -U --allow-untrusted -p $DESTDIR --initdb add alpine-base bash
sudo mount -o bind /dev $DESTDIR/dev
mkdir -p $DESTDIR/etc/apk
echo "$MIRROR/latest-stable/main" > $DESTDIR/etc/apk/repositories
echo "$MIRROR/latest-stable/community" > $DESTDIR/etc/apk/repositories
