#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

ALPINEVER=$(curl --silent https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/latest-releases.yaml | awk '/version/' | tail -1 | awk '{print $2}')

mkdir -p "$CADMIUMROOT/tmp"
ROOTFS_TAR="https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/$ARCH_ALPINE/alpine-minirootfs-$ALPINEVER-$ARCH_ALPINE.tar.gz"
if [ ! -f "$CADMIUMROOT/tmp/alpine-minirootfs-$ALPINEVER-$ARCH_ALPINE.tar.gz" ]; then
	rm $CADMIUMROOT/tmp/alpine-minirootfs-$ALPINEVER-$ARCH_ALPINE.tar.gz || true
	wget "$ROOTFS_TAR" -O $CADMIUMROOT/tmp/alpine-minirootfs-$ALPINEVER-$ARCH_ALPINE.tar.gz
fi
tar xfp $CADMIUMROOT/tmp/alpine-minirootfs-$ALPINEVER-$ARCH_ALPINE.tar.gz -C $DESTDIR

$chroot $DESTDIR $qemu /sbin/apk add alpine-base
$chroot $DESTDIR $qemu /sbin/apk add networkmanager networkmanager-cli networkmanager-tui networkmanager-wifi
$chroot $DESTDIR $qemu setup-devd udev
$chroot $DESTDIR $qemu rc-update add networkmanager default
