name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: build kernel
        uses: ./.github/actions/build/kernel

  build-debian:
    needs: build-kernel
    uses: ./.github/actions/build/rootfs/debian

    
      
