name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: build debian 
        uses: ./.github/actions/workflows/build-debian.yml
    
      
